name: VanishMax
version: '1.0.0'
main: dev.corescode.vanishmax.VanishMaxPlugin
api-version: '1.21'
description: Hierarchical vanish plugin with cextra features for staff comfort & configurable permission levels.
authors: [ CoresCode ]
folia-supported: true

softdepend:
  - LuckPerms
  - PlaceholderAPI

commands:
  invis:
    description: Toggle vanish mode on/off.
    usage: /invis
    aliases: [ vanish, v ]
  vanishmax:
    description: VanishMax admin command.
    usage: /vanishmax reload
    permission: vanishmax.reload

permissions:
  vanishmax.reload:
    description: Allows reloading VanishMax config.
    default: op
  vanishmax.moderator:
    description: Moderator vanish level.
    default: false
  vanishmax.admin:
    description: Admin vanish level.
    default: false
  vanishmax.headadmin:
    description: Head Admin vanish level.
    default: false
  vanishmax.developer:
    description: Developer vanish level - can see everyone in vanish.
    default: false